# Generated by Django 5.1.1 on 2025-02-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_image_after_alter_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
